export default Ember.Object.extend({
    owner: null,
    name: null,
    full_name: null,
    description: null,
    private: null,
    fork: null,
    url: null,
    html_url: null,
    clone_url: null,
    git_url: null,
    ssh_url: null,
    svn_url: null,
    mirror_url: null,
    homepage: null,
    language: null,
    forks_count: null,
    stargazers_count: null,
    watchers_count: null,
    size: null,
    master_branch: null,
    open_issues_count: null,
    pushed_at: null,
    created_at: null,
    updated_at: null,
    subscribers_count: null,
    organization: null,
    parent: null,
    source: null,
    has_issues: null,
    has_wiki: null,
    has_downloads: null,

    buckets: null,
    sizes: null,
    teams: null,

    issues: null
});
